-- Chapters table for storing Quran chapter metadata
CREATE TABLE chapters (
  id SERIAL PRIMARY KEY,
  name_simple TEXT NOT NULL,
  name_complex TEXT NOT NULL,
  name_arabic TEXT NOT NULL,
  transliteration TEXT,
  verse_count INTEGER NOT NULL,
  chapter_type TEXT CHECK (chapter_type IN ('Meccan', 'Medinan'))
);

CREATE INDEX idx_chapters_id ON chapters(id);
CREATE INDEX idx_chapters_verse_count ON chapters(verse_count);
CREATE INDEX idx_chapters_type ON chapters(chapter_type);

-- Insert data from CSV (manual to avoid COPY command limitations)
INSERT INTO chapters (id, name_simple, name_complex, name_arabic, transliteration, verse_count, chapter_type) VALUES
(1, 'Al-Fatihah', 'Al-Fātiḥah', 'الفاتحة', 'Al-Fatihah', 7, 'Meccan'),
(2, 'Al-Baqarah', 'Al-Baqarah', 'البقرة', 'Al-Baqarah', 286, 'Medinan'),
(3, 'Aal-E-Imran', 'Āl ʿImrān', 'آل عمران', 'Aal-E-Imran', 200, 'Medinan'),
(4, 'An-Nisa', 'An-Nisāʾ', 'النساء', 'An-Nisa', 176, 'Medinan'),
(5, 'Al-Ma''idah', 'Al-Māʾidah', 'المائدة', 'Al-Maidah', 120, 'Medinan'),
(6, 'Al-An''am', 'Al-Anʿām', 'الأنعام', 'Al-Anam', 165, 'Meccan'),
(7, 'Al-A''raf', 'Al-Aʿrāf', 'الأعراف', 'Al-Araf', 206, 'Meccan'),
(8, 'Al-Anfal', 'Al-Anfāl', 'الأنفال', 'Al-Anfal', 75, 'Medinan'),
(9, 'At-Tawbah', 'At-Tawbah', 'التوبة', 'At-Tawbah', 129, 'Medinan'),
(10, 'Yunus', 'Yūnus', 'يونس', 'Yunus', 109, 'Meccan'),
(11, 'Hud', 'Hūd', 'هود', 'Hud', 123, 'Meccan'),
(12, 'Yusuf', 'Yūsuf', 'يوسف', 'Yusuf', 111, 'Meccan'),
(13, 'Ar-Ra''d', 'Ar-Raʿd', 'الرعد', 'Ar-Rad', 43, 'Medinan'),
(14, 'Ibrahim', 'Ibrāhīm', 'إبراهيم', 'Ibrahim', 52, 'Meccan'),
(15, 'Al-Hijr', 'Al-Ḥijr', 'الحجر', 'Al-Hijr', 99, 'Meccan'),
(16, 'An-Nahl', 'An-Naḥl', 'النحل', 'An-Nahl', 128, 'Meccan'),
(17, 'Al-Isra', 'Al-Isrāʾ', 'الإسراء', 'Al-Isra', 111, 'Meccan'),
(18, 'Al-Kahf', 'Al-Kahf', 'الكهف', 'Al-Kahf', 110, 'Meccan'),
(19, 'Maryam', 'Maryam', 'مريم', 'Maryam', 98, 'Meccan'),
(20, 'Ta-Ha', 'Ṭā-Hā', 'طه', 'Ta-Ha', 135, 'Meccan'),
(21, 'Al-Anbiya', 'Al-Anbiyāʾ', 'الأنبياء', 'Al-Anbiya', 112, 'Meccan'),
(22, 'Al-Hajj', 'Al-Ḥajj', 'الحج', 'Al-Hajj', 78, 'Medinan'),
(23, 'Al-Mu''minun', 'Al-Muʾminūn', 'المؤمنون', 'Al-Muminun', 118, 'Meccan'),
(24, 'An-Nur', 'An-Nūr', 'النور', 'An-Nur', 64, 'Medinan'),
(25, 'Al-Furqan', 'Al-Furqān', 'الفرقان', 'Al-Furqan', 77, 'Meccan'),
(26, 'Ash-Shu''ara', 'Ash-Shuʿarāʾ', 'الشعراء', 'Ash-Shuara', 227, 'Meccan'),
(27, 'An-Naml', 'An-Naml', 'النمل', 'An-Naml', 93, 'Meccan'),
(28, 'Al-Qasas', 'Al-Qaṣaṣ', 'القصص', 'Al-Qasas', 88, 'Meccan'),
(29, 'Al-Ankabut', 'Al-ʿAnkabūt', 'العنكبوت', 'Al-Ankabut', 69, 'Meccan'),
(30, 'Ar-Rum', 'Ar-Rūm', 'الروم', 'Ar-Rum', 60, 'Meccan'),
(31, 'Luqman', 'Luqmān', 'لقمان', 'Luqman', 34, 'Meccan'),
(32, 'As-Sajdah', 'As-Sajdah', 'السجدة', 'As-Sajdah', 30, 'Meccan'),
(33, 'Al-Ahzab', 'Al-Aḥzāb', 'الأحزاب', 'Al-Ahzab', 73, 'Medinan'),
(34, 'Saba', 'Sabaʾ', 'سبأ', 'Saba', 54, 'Meccan'),
(35, 'Fatir', 'Fāṭir', 'فاطر', 'Fatir', 45, 'Meccan'),
(36, 'Ya-Sin', 'Yā-Sīn', 'يس', 'Ya-Sin', 83, 'Meccan'),
(37, 'As-Saffat', 'Aṣ-Ṣāffāt', 'الصافات', 'As-Saffat', 182, 'Meccan'),
(38, 'Sad', 'Ṣād', 'ص', 'Sad', 88, 'Meccan'),
(39, 'Az-Zumar', 'Az-Zumar', 'الزمر', 'Az-Zumar', 75, 'Meccan'),
(40, 'Ghafir', 'Ghāfir', 'غافر', 'Ghafir', 85, 'Meccan'),
(41, 'Fussilat', 'Fussilat', 'فصلت', 'Fussilat', 54, 'Meccan'),
(42, 'Ash-Shura', 'Ash-Shūrā', 'الشورى', 'Ash-Shura', 53, 'Meccan'),
(43, 'Az-Zukhruf', 'Az-Zukhruf', 'الزخرف', 'Az-Zukhruf', 89, 'Meccan'),
(44, 'Ad-Dukhan', 'Ad-Dukhān', 'الدخان', 'Ad-Dukhan', 59, 'Meccan'),
(45, 'Al-Jathiyah', 'Al-Jāthiyah', 'الجاثية', 'Al-Jathiyah', 37, 'Meccan'),
(46, 'Al-Ahqaf', 'Al-Aḥqāf', 'الأحقاف', 'Al-Ahqaf', 35, 'Meccan'),
(47, 'Muhammad', 'Muḥammad', 'محمد', 'Muhammad', 38, 'Medinan'),
(48, 'Al-Fath', 'Al-Fatḥ', 'الفتح', 'Al-Fath', 29, 'Medinan'),
(49, 'Al-Hujurat', 'Al-Ḥujurāt', 'الحجرات', 'Al-Hujurat', 18, 'Medinan'),
(50, 'Qaf', 'Qāf', 'ق', 'Qaf', 45, 'Meccan'),
(51, 'Adh-Dhariyat', 'Adh-Dhāriyāt', 'الذاريات', 'Adh-Dhariyat', 60, 'Meccan'),
(52, 'At-Tur', 'Aṭ-Ṭūr', 'الطور', 'At-Tur', 49, 'Meccan'),
(53, 'An-Najm', 'An-Najm', 'النجم', 'An-Najm', 62, 'Meccan'),
(54, 'Al-Qamar', 'Al-Qamar', 'القمر', 'Al-Qamar', 55, 'Meccan'),
(55, 'Ar-Rahman', 'Ar-Raḥmān', 'الرحمن', 'Ar-Rahman', 78, 'Medinan'),
(56, 'Al-Waqi''ah', 'Al-Wāqiʿah', 'الواقعة', 'Al-Waqiah', 96, 'Meccan'),
(57, 'Al-Hadid', 'Al-Ḥadīd', 'الحديد', 'Al-Hadid', 29, 'Medinan'),
(58, 'Al-Mujadila', 'Al-Mujādilah', 'المجادلة', 'Al-Mujadila', 22, 'Medinan'),
(59, 'Al-Hashr', 'Al-Ḥashr', 'الحشر', 'Al-Hashr', 24, 'Medinan'),
(60, 'Al-Mumtahanah', 'Al-Mumtaḥanah', 'الممتحنة', 'Al-Mumtahanah', 13, 'Medinan'),
(61, 'As-Saff', 'Aṣ-Ṣaff', 'الصف', 'As-Saff', 14, 'Medinan'),
(62, 'Al-Jumu''ah', 'Al-Jumuʿah', 'الجمعة', 'Al-Jumuah', 11, 'Medinan'),
(63, 'Al-Munafiqun', 'Al-Munāfiqūn', 'المنافقون', 'Al-Munafiqun', 11, 'Medinan'),
(64, 'At-Taghabun', 'At-Taghābun', 'التغابن', 'At-Taghabun', 18, 'Medinan'),
(65, 'At-Talaq', 'Aṭ-Ṭalāq', 'الطلاق', 'At-Talaq', 12, 'Medinan'),
(66, 'At-Tahrim', 'At-Taḥrīm', 'التحريم', 'At-Tahrim', 12, 'Medinan'),
(67, 'Al-Mulk', 'Al-Mulk', 'الملك', 'Al-Mulk', 30, 'Meccan'),
(68, 'Al-Qalam', 'Al-Qalam', 'القلم', 'Al-Qalam', 52, 'Meccan'),
(69, 'Al-Haqqah', 'Al-Ḥāqqah', 'الحاقة', 'Al-Haqqah', 52, 'Meccan'),
(70, 'Al-Ma''arij', 'Al-Maʿārij', 'المعارج', 'Al-Maarij', 44, 'Meccan'),
(71, 'Nuh', 'Nūḥ', 'نوح', 'Nuh', 28, 'Meccan'),
(72, 'Al-Jinn', 'Al-Jinn', 'الجن', 'Al-Jinn', 28, 'Meccan'),
(73, 'Al-Muzzammil', 'Al-Muzzammil', 'المزمل', 'Al-Muzzammil', 20, 'Meccan'),
(74, 'Al-Muddathir', 'Al-Muddaththir', 'المدثر', 'Al-Muddathir', 56, 'Meccan'),
(75, 'Al-Qiyamah', 'Al-Qiyāmah', 'القيامة', 'Al-Qiyamah', 40, 'Meccan'),
(76, 'Al-Insan', 'Al-Insān', 'الإنسان', 'Al-Insan', 31, 'Medinan'),
(77, 'Al-Mursalat', 'Al-Mursalāt', 'المرسلات', 'Al-Mursalat', 50, 'Meccan'),
(78, 'An-Naba', 'An-Nabaʾ', 'النبأ', 'An-Naba', 40, 'Meccan'),
(79, 'An-Nazi''at', 'An-Nāziʿāt', 'النازعات', 'An-Naziat', 46, 'Meccan'),
(80, 'Abasa', 'ʿAbasa', 'عبس', 'Abasa', 42, 'Meccan'),
(81, 'At-Takwir', 'At-Takwīr', 'التكوير', 'At-Takwir', 29, 'Meccan'),
(82, 'Al-Infitar', 'Al-Infiṭār', 'الانفطار', 'Al-Infitar', 19, 'Meccan'),
(83, 'Al-Mutaffifin', 'Al-Muṭaffifīn', 'المطففين', 'Al-Mutaffifin', 36, 'Meccan'),
(84, 'Al-Inshiqaq', 'Al-Inshiqāq', 'الانشقاق', 'Al-Inshiqaq', 25, 'Meccan'),
(85, 'Al-Buruj', 'Al-Burūj', 'البروج', 'Al-Buruj', 22, 'Meccan'),
(86, 'At-Tariq', 'Aṭ-Ṭāriq', 'الطارق', 'At-Tariq', 17, 'Meccan'),
(87, 'Al-A''la', 'Al-Aʿlā', 'الأعلى', 'Al-Ala', 19, 'Meccan'),
(88, 'Al-Ghashiyah', 'Al-Ghāshiyah', 'الغاشية', 'Al-Ghashiyah', 26, 'Meccan'),
(89, 'Al-Fajr', 'Al-Fajr', 'الفجر', 'Al-Fajr', 30, 'Meccan'),
(90, 'Al-Balad', 'Al-Balad', 'البلد', 'Al-Balad', 20, 'Meccan'),
(91, 'Ash-Shams', 'Ash-Shams', 'الشمس', 'Ash-Shams', 15, 'Meccan'),
(92, 'Al-Layl', 'Al-Layl', 'الليل', 'Al-Layl', 21, 'Meccan'),
(93, 'Ad-Duha', 'Aḍ-Ḍuḥā', 'الضحى', 'Ad-Duha', 11, 'Meccan'),
(94, 'Ash-Sharh', 'Ash-Sharḥ', 'الشرح', 'Al-Sharh', 8, 'Meccan'),
(95, 'At-Tin', 'At-Tīn', 'التين', 'At-Tin', 8, 'Meccan'),
(96, 'Al-Alaq', 'Al-ʿAlaq', 'العلق', 'Al-Alaq', 19, 'Meccan'),
(97, 'Al-Qadr', 'Al-Qadr', 'القدر', 'Al-Qadr', 5, 'Meccan'),
(98, 'Al-Bayyinah', 'Al-Bayyinah', 'البينة', 'Al-Bayyinah', 8, 'Medinan'),
(99, 'Az-Zalzalah', 'Az-Zalzalah', 'الزلزلة', 'Az-Zalzalah', 8, 'Medinan'),
(100, 'Al-Adiyat', 'Al-ʿĀdiyāt', 'العاديات', 'Al-Adiyat', 11, 'Meccan'),
(101, 'Al-Qari''ah', 'Al-Qāriʿah', 'القارعة', 'Al-Qariah', 11, 'Meccan'),
(102, 'At-Takathur', 'At-Takāthur', 'التكاثر', 'At-Takathur', 8, 'Meccan'),
(103, 'Al-Asr', 'Al-ʿAṣr', 'العصر', 'Al-Asr', 3, 'Meccan'),
(104, 'Al-Humazah', 'Al-Humazah', 'الهمزة', 'Al-Humazah', 9, 'Meccan'),
(105, 'Al-Fil', 'Al-Fīl', 'الفيل', 'Al-Fil', 5, 'Meccan'),
(106, 'Quraysh', 'Quraysh', 'قريش', 'Quraysh', 4, 'Meccan'),
(107, 'Al-Ma''un', 'Al-Māʿūn', 'الماعون', 'Al-Maun', 7, 'Meccan'),
(108, 'Al-Kawthar', 'Al-Kawthar', 'الكوثر', 'Al-Kawthar', 3, 'Meccan'),
(109, 'Al-Kafirun', 'Al-Kāfirūn', 'الكافرون', 'Al-Kafirun', 6, 'Meccan'),
(110, 'An-Nasr', 'An-Naṣr', 'النصر', 'An-Nasr', 3, 'Medinan'),
(111, 'Al-Masad', 'Al-Masad', 'المسد', 'Al-Masad', 5, 'Meccan'),
(112, 'Al-Ikhlas', 'Al-Ikhlāṣ', 'الإخلاص', 'Al-Ikhlas', 4, 'Meccan'),
(113, 'Al-Falaq', 'Al-Falaq', 'الفلق', 'Al-Falaq', 5, 'Meccan'),
(114, 'An-Nas', 'An-Nās', 'الناس', 'An-Nas', 6, 'Meccan');
